enyo.depends(
	"thirdparty/",
	"Sidebar.js",
	"TimelineView.js",
    "MainView.js",
    "CommentsView.js",
    "StatusesView.js",
    "UserView.js",
    "UserListView.js",
    "DetailUserListView.js",
    "Login.js",
    "Splash.js",
    "WeiboUtil.js"
);